### ISSUE TITLE
UI/UX Design

### ISSUE THREAD

**Issue by LukasStrickler** [LukasStrickler/FixMyTown#14]
Create UI/UX Wireframe in *excalidraw* in `docs/uiux` for all views

- User
   - [ ] Dashboard Overview
   - [ ] Reporting
      - [ ] Create
      - [ ] Edit
      - [ ] Review
- Worker
   - [ ] Dashboard Overview
   - [ ] Reporting Review/Process
- Admin
   - User Management
       - [ ] Overview
       - [ ] Create
       - [ ] Edit
       - [ ] Delete

**Comment by paulKlarer** [comment]
[excalidraw link](https://excalidraw.com/#room=5e166163f01b51f19a9a,EM19vcRi-vAtVrz8uc0Y-A)
