### ISSUE TITLE
Prepare Reporting Email templates

### ISSUE THREAD

**Issue by LukasStrickler** [LukasStrickler/FixMyTown#16]
use `React.Email` to create all email templates in `src/components/email`

- Reporting
    - [x] Report Notice (when submitted)
    - [x] Status Update (on in fixing, on completed)

**Comment by LukasStrickler** [comment]
blocked by #13 and #15

**Comment by joscha-st** [comment]
Location changed to `src/emails`

Also, do we really want a monthly report?
